const lessons = {
  0: [
    {de: "der Jemen", ru: "-"},
    {de: "der Sudan", ru: "-"},
    {de: "die Schweiz", ru: "-"},
    {de: "die Türkei", ru: "-"},
    {de: "die USA (pl.)", ru: "Vereinigte Staaten von Amerika"},
    {de: "da, hier", ru: "здесь (da hinten steht ein Auto)"},
    {de: "dort", ru: "там"},
    {de: "drinnen", ru: "внутри (da es regnet, bleiben wir drinnen)"},
    {de: "hinten", ru: "сзади (da hinten steht ein Auto)"},
    {de: "die Stadt → die Städte", ru: "город"},
    {de: "das Land, die Länder", ru: "страна"},
    {de: "buchstabieren", ru: "hláskovat"},
    {de: "", ru: ""},
    {de: "", ru: ""},
    {de: "", ru: ""},
    {de: "", ru: ""},
    {de: "", ru: ""},
    {de: "", ru: ""},
    {de: "", ru: ""},
    {de: "", ru: ""},
    {de: "", ru: ""}
  ],

  1: [
    {de: "der Abend, -e", ru: "večer"},
    {de: "Guten Abend!", ru: "Dobrý večer!"},
    {de: "gut", ru: "dobrý"},
    {de: "Guten Abend!", ru: "Dobrý večer!"},
    {de: "gut", ru: "dobrý"},
    {de: "Hallo!, Hi!", ru: "Ahoj!"},
    {de: "heißen", ru: "jmenovat se"},
    {de: "ja", ru: "ano"},
    {de: "der Morgen", ru: "ráno"},
    {de: "Guten Morgen!", ru: "Dobré ráno!"},
    {de: "der Name, -n", ru: "jméno"},
    {de: "nein", ru: "ne"},
    {de: "sein", ru: "být"},
    {de: "der Tag, -e", ru: "den"},
    {de: "Guten Tag!", ru: "Dobrý den!"},
    {de: "und", ru: "a"},
    {de: "wer?", ru: "kdo?"},
    {de: "Wer bist du?", ru: "Kdo jsi?"},
    {de: "wie?", ru: "jak?"},
    {de: "Wie heißt du?", ru: "Jak se jmenuješ?"},
    {de: "in", ru: "v"},
    {de: "in der Nähe (von…)", ru: "nedaleko (čeho)"},
    {de: "das Spiel, -e", ru: "hra"},
    {de: "wo?", ru: "kde?"},
    {de: "Wo wohnst du?", ru: "Kde bydlíš?"},
    {de: "wohnen", ru: "bydlet"},
    {de: "null", ru: "0"},
    {de: "eins", ru: "1"},
    {de: "zwei", ru: "2"},
    {de: "drei", ru: "3"},
    {de: "vier", ru: "4"},
    {de: "fünf", ru: "5"},
    {de: "sechs", ru: "6"},
    {de: "sieben", ru: "7"},
    {de: "acht", ru: "8"},
    {de: "neun", ru: "9"},
    {de: "zehn", ru: "10"},
    {de: "elf", ru: "11"},
    {de: "zwölf", ru: "12"},
    {de: "dreizehn", ru: "13"},
    {de: "vierzehn", ru: "14"},
    {de: "fünfzehn", ru: "15"},
    {de: "sechzehn", ru: "16"},
    {de: "siebzehn", ru: "17"},
    {de: "achtzehn", ru: "18"},
    {de: "neunzehn", ru: "19"},
    {de: "zwanzig", ru: "20"},
    {de: "alt", ru: "starý"},
    {de: "der Monat, -e", ru: "měsíc"},
    {de: "aber", ru: "ale"},
    {de: "das Alter, -", ru: "věk"},
    {de: "auch", ru: "také"},
    {de: "aus", ru: "z"},
    {de: "die Band, -s", ru: "(hudební) skupina"},
    {de: "chatten (č)", ru: "chatovat"},
    {de: "das Computerspiel, -e", ru: "počítačová hra"},
    {de: "die/das E-mail, -s", ru: "e-mail"},
    {de: "das Englisch", ru: "angličtina, anglicky"},
    {de: "der Fan, -s", ru: "fanoušek"},
    {de: "das Französisch", ru: "francouzština, francouzsky"},
    {de: "der Freund, -e", ru: "kamarád"},
    {de: "die Freundin, -nen", ru: "kamarádka"},
    {de: "der Fußball", ru: "fotbal"},
    {de: "gehen", ru: "jít"},
    {de: "gern", ru: "rád/a"},
    {de: "die Gitarre, -n", ru: "kytara"},
    {de: "das Handy, -s", ru: "mobil"},
    {de: "das Hobby, -s", ru: "koníček"},
    {de: "hören", ru: "poslouchat"},
    {de: "im Internet surfen", ru: "surfovat na internetu"},
    {de: "immer", ru: "pořád, neustále"},
    {de: "das Jahr, -e", ru: "rok"},
    {de: "kein/keine/kein", ru: "žádný/žádná/žádné"},
    {de: "das Klavier, -e", ru: "klavír"},
    {de: "kommen (aus)", ru: "pocházet (z)"},
    {de: "das Konzert, -e", ru: "koncert"},
    {de: "lernen", ru: "učit se"},
    {de: "liegen", ru: "ležet"},
    {de: "der Nachname, -n", ru: "příjmení"},
    {de: "nicht weit von", ru: "nedaleko (koho, čeho)"},
    {de: "reisen", ru: "cestovat"},
    {de: "schreiben", ru: "psát"},
    {de: "die Schule, -n", ru: "škola"},
    {de: "spielen", ru: "hrát"},
    {de: "tanzen", ru: "tancovat"},
    {de: "der Vorname, -n", ru: "křestní jméno"},
    {de: "der Wohnort", ru: "bydliště"},
    {de: "falsch", ru: "nesprávně"},
    {de: "die Flöte, -n", ru: "flétna"},
    {de: "haben", ru: "mít"},
    {de: "das Instrument, -e", ru: "(hudební) nástroj"},
    {de: "jetzt", ru: "teď"},
    {de: "machen", ru: "dělat"},
    {de: "richtig", ru: "správně"},
    {de: "der Sport", ru: "sport"},
    {de: "Sport treiben", ru: "sportovat"},
    {de: "das Squash", ru: "squash"},
    {de: "das/der Yoga", ru: "jóga"},
    {de: "bald", ru: "brzy"},
    {de: "Bis bald!", ru: "Brzy na shledanou!"},
    {de: "bis", ru: "do (čas)"},
    {de: "Bis zum nächsten Mal!", ru: "(Uvidíme se) příště!"},
    {de: "die Frau, -en", ru: "paní"},
    {de: "der Herr, -en", ru: "pan"},
    {de: "Mach's gut!", ru: "Měj se (hezky)!"},
    {de: "das Museum, die Museen", ru: "muzeum"},
    {de: "schön", ru: "hezký"}
  ],
  2: [
    {de: "", ru: ""}
  ],
  3: [
    {de: "", ru: ""}
  ]
};