const lessons = {
  Nastyy: [
    {de: "der Jemen", ru: "Jemen"},
    {de: "der Sudan", ru: "Súdán"},
    {de: "die Schweiz", ru: "Švýcarsko"},
    {de: "die Türkei", ru: "Turecko"},
    {de: "die USA (pl.) - Vereinigte Staaten von Amerika", ru: "USA"},
    {de: "da, hier - da hinten steht ein Auto", ru: "здесь"},
    {de: "dort", ru: "там"},
    {de: "drinnen - da es regnet, bleiben wir drinnen", ru: "внутри"},
    {de: "hinten - da hinten steht ein Auto", ru: "сзади"},
    {de: "die Stadt → die Städte", ru: "город"},
    {de: "das Land, die Länder", ru: "страна"},
    {de: "buchstabieren", ru: "hláskovat"},
    {de: "die Begrüßung, -en", ru: "pozdrav"},
    {de: "der Abschied, -e", ru: "loučení"},
    {de: "die Herkunft", ru: "происхождение"},
    {de: "die Sprache (was?)", ru: "jazyk"},
    {de: "zwischendurch mal - Ich trinke zwischendurch mal einen Kaffee, Zwischendurch mal Pause machen ist wichtig", ru: "время от времени, иногда, между делом"},
    {de: "vergleichen", ru: "porovnávat"},
    {de: "die Großeltern (Plural)", ru: "бабушка и дедушка"},
    {de: "der Großvater, die Großväter", ru: "дедушка"},
    {de: "der Opa, -s", ru: "дедушка (разг.)"},
    {de: "die Großmutter, die Großmütter", ru: "бабушка"},
    {de: "die Oma, -s", ru: "бабушка (разг.)"},
    {de: "die Eltern (Plural)", ru: "родители"},
    {de: "der Vater, die Väter", ru: "отец"},
    {de: "die Mutter, die Mütter", ru: "мать"},
    {de: "das Kind, -er", ru: "ребёнок"},
    {de: "die Tochter, die Töchter", ru: "дочь"},
    {de: "der Sohn, die Söhne", ru: "сын"},
    {de: "die Enkelkinder (Plural)", ru: "внуки"},
    {de: "die Enkelin, -nen", ru: "внучка"},
    {de: "der Enkel, -", ru: "внук"},
    {de: "die Geschwister (Plural)", ru: "братья и сёстры"},
    {de: "die Schwester, -n", ru: "сестра"},
    {de: "der Bruder, die Brüder", ru: "брат"},
    {de: "weitere Verwandte (Plural)", ru: "другие родственники"},
    {de: "die Tante, -n", ru: "тётя"},
    {de: "der Onkel, -", ru: "дядя"},
    {de: "der Cousin, -s", ru: "кузен"},
    {de: "die Cousine, -n", ru: "кузина"},
    {de: "die Nichte, -n", ru: "племянница"},
    {de: "der Neffe, -n", ru: "племянник"},
    {de: "der Verwandte, -n", ru: "родственник"},
    {de: "die Verwandte, -n", ru: "родственница"},
    {de: "der Ehemann, die Ehemänner", ru: "муж"},
    {de: "die Ehefrau, die Ehefrauen", ru: "жена"},
    {de: "der Junge, -n", ru: "мальчик"},
    {de: "das Mädchen, -", ru: "девочка"},
    {de: "der Mann, Männer", ru: "мужчина"},
    {de: "die Frau, -en", ru: "женщина"},
    {de: "geschieden", ru: "в разводе"},
    {de: "verheiratet", ru: "в браке"},
    {de: "ledig", ru: "не замужем"},
    {de: "verwitwet", ru: "вдовец / вдова"},
    {de: "zurzeit", ru: "в настоящее время, сейчас"},
    {de: "der Norden", ru: "север"},
    {de: "der Süden", ru: "юг"},
    {de: "der Westen", ru: "запад"},
    {de: "der Osten", ru: "восток"},
    {de: "seit + Dativ - ich lerne seit einem Monat Deutsch., sie arbeitet seit 2010 hier.", ru: "с момента"},
    {de: "meinen", ru: "думать, считать, иметь в виду"},
    {de: "lecker", ru: "вкусный"},
    {de: "vielleicht", ru: "возможно"},
    {de: "das Mehl, -", ru: "мука"},
    {de: "das Ei, -er", ru: "яйцо"},
    {de: "die Banane, -n", ru: "банан"},
    {de: "der Apfel, Äpfel", ru: "яблоко"},
    {de: "die Orange, -n", ru: "апельсин"},
    {de: "der Kuchen, -", ru: "пирог"},
    {de: "der Kaffee, -s", ru: "кофе"},
    {de: "der Saft, Säfte", ru: "сок"},
    {de: "das Brötchen, -", ru: "булочка"},
    {de: "das Würstchen, -", ru: "сосиска"},
    {de: "die Birne, -n", ru: "груша"},
    {de: "die Tomate, -n", ru: "помидор"},
    {de: "die Kiwi, -s", ru: "киви"},
    {de: "der Pfannkuchen, -", ru: "блин"},
    {de: "das Brot, -e", ru: "хлеб"},
    {de: "die Kartoffel, -n", ru: "картофель"},
    {de: "der Joghurt, -s", ru: "йогурт"},
    {de: "die Zwiebel, -n", ru: "лук"},
    {de: "der Fisch, -e", ru: "рыба"},
    {de: "das Fleisch, -", ru: "мясо"},
    {de: "das Bier, -e", ru: "пиво"},
    {de: "der Wein, -e", ru: "вино"},
    {de: "das Mineralwasser, -", ru: "минеральная вода"},
    {de: "der Käse, -", ru: "сыр"},
    {de: "das Salz, -e", ru: "соль"},
    {de: "der Zucker, -", ru: "сахар"},
    {de: "der Tee, -s", ru: "чай"},
    {de: "das Obst, -", ru: "фрукты"},
    {de: "das Gemüse, -", ru: "овощи"},
    {de: "der Reis, -", ru: "рис"},
    {de: "die Milch, -", ru: "молоко"},
    {de: "die Butter, -", ru: "масло"},
    {de: "das Öl, -e", ru: "масло растительное"},
    {de: "die Gurke, -n", ru: "огурец"},
    {de: "die Paprika, -s", ru: "перец сладкий"},
    {de: "das Hähnchen, -", ru: "курица"},
    {de: "die Wurst, Würste", ru: "колбаса"},
    {de: "die Schokolade, -n", ru: "шоколад"},
    {de: "sonst (Komm jetzt, sonst verpassen wir den Zug., Hast du sonst noch etwas?, Alles sonst in Ordnung?", ru: "иначе, в противном случае, ещё, кроме того, обычно, обычно-то (в устойчивых выражениях)"},
    {de: "der Einkaufszettel, -", ru: "список покупок"}
  ],

  1: [
    {de: "der Abend, -e", ru: "večer"},
    {de: "Guten Abend!", ru: "Dobrý večer!"},
    {de: "gut", ru: "dobrý"},
    {de: "Guten Abend!", ru: "Dobrý večer!"},
    {de: "gut", ru: "dobrý"},
    {de: "Hallo!, Hi!", ru: "Ahoj!"},
    {de: "heißen", ru: "jmenovat se"},
    {de: "ja", ru: "ano"},
    {de: "der Morgen", ru: "ráno"},
    {de: "Guten Morgen!", ru: "Dobré ráno!"},
    {de: "der Name, -n", ru: "jméno"},
    {de: "nein", ru: "ne"},
    {de: "sein", ru: "být"},
    {de: "der Tag, -e", ru: "den"},
    {de: "Guten Tag!", ru: "Dobrý den!"},
    {de: "und", ru: "a"},
    {de: "wer?", ru: "kdo?"},
    {de: "Wer bist du?", ru: "Kdo jsi?"},
    {de: "wie?", ru: "jak?"},
    {de: "Wie heißt du?", ru: "Jak se jmenuješ?"},
    {de: "in", ru: "v"},
    {de: "in der Nähe (von…)", ru: "nedaleko (čeho)"},
    {de: "das Spiel, -e", ru: "hra"},
    {de: "wo?", ru: "kde?"},
    {de: "Wo wohnst du?", ru: "Kde bydlíš?"},
    {de: "wohnen", ru: "bydlet"},
    {de: "null", ru: "0"},
    {de: "eins", ru: "1"},
    {de: "zwei", ru: "2"},
    {de: "drei", ru: "3"},
    {de: "vier", ru: "4"},
    {de: "fünf", ru: "5"},
    {de: "sechs", ru: "6"},
    {de: "sieben", ru: "7"},
    {de: "acht", ru: "8"},
    {de: "neun", ru: "9"},
    {de: "zehn", ru: "10"},
    {de: "elf", ru: "11"},
    {de: "zwölf", ru: "12"},
    {de: "dreizehn", ru: "13"},
    {de: "vierzehn", ru: "14"},
    {de: "fünfzehn", ru: "15"},
    {de: "sechzehn", ru: "16"},
    {de: "siebzehn", ru: "17"},
    {de: "achtzehn", ru: "18"},
    {de: "neunzehn", ru: "19"},
    {de: "zwanzig", ru: "20"},
    {de: "alt", ru: "starý"},
    {de: "der Monat, -e", ru: "měsíc"},
    {de: "aber", ru: "ale"},
    {de: "das Alter, -", ru: "věk"},
    {de: "auch", ru: "také"},
    {de: "aus", ru: "z"},
    {de: "die Band, -s", ru: "(hudební) skupina"},
    {de: "chatten (č)", ru: "chatovat"},
    {de: "das Computerspiel, -e", ru: "počítačová hra"},
    {de: "die/das E-mail, -s", ru: "e-mail"},
    {de: "das Englisch", ru: "angličtina, anglicky"},
    {de: "der Fan, -s", ru: "fanoušek"},
    {de: "das Französisch", ru: "francouzština, francouzsky"},
    {de: "der Freund, -e", ru: "kamarád"},
    {de: "die Freundin, -nen", ru: "kamarádka"},
    {de: "der Fußball", ru: "fotbal"},
    {de: "gehen", ru: "jít"},
    {de: "gern", ru: "rád/a"},
    {de: "die Gitarre, -n", ru: "kytara"},
    {de: "das Handy, -s", ru: "mobil"},
    {de: "das Hobby, -s", ru: "koníček"},
    {de: "hören", ru: "poslouchat"},
    {de: "im Internet surfen", ru: "surfovat na internetu"},
    {de: "immer", ru: "pořád, neustále"},
    {de: "das Jahr, -e", ru: "rok"},
    {de: "kein/keine/kein", ru: "žádný/žádná/žádné"},
    {de: "das Klavier, -e", ru: "klavír"},
    {de: "kommen (aus)", ru: "pocházet (z)"},
    {de: "das Konzert, -e", ru: "koncert"},
    {de: "lernen", ru: "učit se"},
    {de: "liegen", ru: "ležet"},
    {de: "der Nachname, -n", ru: "příjmení"},
    {de: "nicht weit von", ru: "nedaleko (koho, čeho)"},
    {de: "reisen", ru: "cestovat"},
    {de: "schreiben", ru: "psát"},
    {de: "die Schule, -n", ru: "škola"},
    {de: "spielen", ru: "hrát"},
    {de: "tanzen", ru: "tancovat"},
    {de: "der Vorname, -n", ru: "křestní jméno"},
    {de: "der Wohnort", ru: "bydliště"},
    {de: "falsch", ru: "nesprávně"},
    {de: "die Flöte, -n", ru: "flétna"},
    {de: "haben", ru: "mít"},
    {de: "das Instrument, -e", ru: "(hudební) nástroj"},
    {de: "jetzt", ru: "teď"},
    {de: "machen", ru: "dělat"},
    {de: "richtig", ru: "správně"},
    {de: "der Sport", ru: "sport"},
    {de: "Sport treiben", ru: "sportovat"},
    {de: "das Squash", ru: "squash"},
    {de: "das/der Yoga", ru: "jóga"},
    {de: "bald", ru: "brzy"},
    {de: "Bis bald!", ru: "Brzy na shledanou!"},
    {de: "bis", ru: "do (čas)"},
    {de: "Bis zum nächsten Mal!", ru: "(Uvidíme se) příště!"},
    {de: "die Frau, -en", ru: "paní"},
    {de: "der Herr, -en", ru: "pan"},
    {de: "Mach's gut!", ru: "Měj se (hezky)!"},
    {de: "das Museum, die Museen", ru: "muzeum"},
    {de: "schön", ru: "hezký"}
  ],

  EG 1 - Los geht's!: [
    {de: "der Korken", ru: "the cork"},
    {de: "mitbringen", ru: "bring along"},
    {de: "üben", ru: "rehearse"},
    {de: "deutlich", ru: "distinctly"},
    {de: "bekloppt", ru: "nutty"},
    {de: "die Aufnahme", ru: "the recording"},
    {de: "aufregend", ru: "excitingly"},
    {de: "ehrlich gesagt", ru: "to be honest"},
    {de: "nachdenken", ru: "ponder"},
    {de: "kompliziert", ru: "complicated"},
    {de: "arbeitsintensiv", ru: "labor-intensive"},
    {de: "ins Leben rufen", ru: "bring to life"},
    {de: "erklären", ru: "explain"},
    {de: "vorhaben", ru: "have in mind"},
    {de: "herausfinden", ru: "find out"},
    {de: "die Liste", ru: "the list"},
    {de: "im Laufe", ru: "in the course of"},
    {de: "die Erinnerung", ru: "the reminder"},
    {de: "leise", ru: "silent"},
    {de: "wöchentlich", ru: "on a weekly basis"},
    {de: "der Grund", ru: "the reason"},
    {de: "zu Hause", ru: "at home"},
    {de: "anschauen", ru: "watch"},
    {de: "der Produzent", ru: "the producer"},
    {de: "der Regisseur", ru: "the director"},
    {de: "besitzen", ru: "own"},
    {de: "betrachten", ru: "look at"},
    {de: "bieten", ru: "offer"},
    {de: "einstündig", ru: "one-hour"},
    {de: "das Putzen", ru: "cleaning"},
    {de: "schwierig", ru: "difficult"},
    {de: "das Auge", ru: "the eye"},
    {de: "das Ohr", ru: "the ear"},
    {de: "das Spazierengehen", ru: "walking around"},
    {de: "hilfreich", ru: "helpful"},
    {de: "vorspielen", ru: "play"},
    {de: "der Tipp", ru: "the tip"},
    {de: "die Sprache", ru: "the language"},
    {de: "umgeben", ru: "surround"},
    {de: "hören", ru: "hear"},
    {de: "das Wort", ru: "the word"},
    {de: "verstehen", ru: "comprehend"},
    {de: "der Rhythmus", ru: "the rhythm"},
    {de: "die Melodie", ru: "the melody"},
    {de: "das Wichtigste", ru: "the most important thing"},
    {de: "Polnisch", ru: "Polish"},
    {de: "Polen", ru: "Poland"},
    {de: "verinnerlichen", ru: "internalize"},
    {de: "das Gefühl", ru: "the feeling"},
    {de: "aufschnappen", ru: "overhear"},
    {de: "drauflos", ru: "straight on"},
    {de: "plappern", ru: "babble"},
    {de: "imitieren", ru: "imitate"},
    {de: "die Übung", ru: "the exercise"},
    {de: "sich beteiligen", ru: "get involved"},
    {de: "ausdenken", ru: "think up"},
    {de: "das Ding", ru: "the thing"},
    {de: "zweisprachig", ru: "bilingual"},
    {de: "der Untertitel", ru: "the subtitle"},
    {de: "ähnlich", ru: "similar"},
    {de: "funktionieren", ru: "function"},
    {de: "unterstützen", ru: "support"},
    {de: "beim Abspielen", ru: "during playback"},
    {de: "die wichtigsten", ru: "the most important"},
    {de: "die Übersetzung", ru: "the translation"},
    {de: "verstehen", ru: "understand"},
    {de: "erfordern", ru: "require"},
    {de: "funktionieren", ru: "work"},
    {de: "alle", ru: "everyone"},
    {de: "verfügbar", ru: "available"},
    {de: "empfehlen", ru: "recommend"},
    {de: "das Handy", ru: "mobile phone"},
    {de: "helfen", ru: "be of help"},
    {de: "sensationell", ru: "awesome"},
    {de: "aussehen", ru: "look like"},
    {de: "der Zuschauer", ru: "the viewer"},
    {de: "der Zuhörer", ru: "the listener"},
    {de: "in der Sprache bleiben", ru: "stay in the language"},
    {de: "Sinn machen", ru: "make sense"},
    {de: "unterwegs sein", ru: "be out and about"},
    {de: "Niederländisch", ru: "Dutch"},
    {de: "erschließen", ru: "deduce"},
    {de: "unbedingt", ru: "absolutely"},
    {de: "nachgucken", ru: "have a look"},
    {de: "Spaß machen", ru: "be fun"},
    {de: "aufschreiben", ru: "write down"},
    {de: "merken", ru: "memorize"},
    {de: "zur Verfügung stellen", ru: "make available"},
    {de: "mitlesen", ru: "read along"},
    {de: "das Angebot", ru: "the offer"},
    {de: "echt", ru: "authentic"},
    {de: "untereinander", ru: "among ourselves"},
    {de: "mehr oder weniger", ru: "more or less"},
    {de: "die Geschwindigkeit", ru: "the speed"},
    {de: "langsamer", ru: "slower"},
    {de: "kostenlos", ru: "free"},
    {de: "die Leute", ru: "the people"},
    {de: "profitieren", ru: "benefit"},
    {de: "die Arbeit", ru: "the work"},
    {de: "die Vokabelhilfe", ru: "the vocabulary help"},
    {de: "die Einnahme", ru: "the income"},
    {de: "verweisen", ru: "refer"},
    {de: "anfangen", ru: "get started"},
    {de: "das Thema", ru: "the topic"},
    {de: "die Woche", ru: "the week"},
    {de: "die Zeit", ru: "the time"},
    {de: "das Segment", ru: "the segment"},
    {de: "nahebringen", ru: "familiarize"},
    {de: "die Überraschung", ru: "the surprise"},
    {de: "verpassen", ru: "miss"},
    {de: "die Dankbarkeit", ru: "the gratitude"},
    {de: "der Zufall", ru: "the coincidence"},
    {de: "bestimmen", ru: "determine"},
    {de: "auswählen", ru: "pick"},
    {de: "verrückt", ru: "insane"},
    {de: "im Vergleich", ru: "by comparison"},
    {de: "zugeben", ru: "admit"},
    {de: "grob", ru: "roughly"},
    {de: "die Sendung", ru: "the broadcast"},
    {de: "der Streit", ru: "the dispute"},
    {de: "das Geld", ru: "the money"},
    {de: "das Hörbuch", ru: "the audio book"},
    {de: "klarstellen", ru: "clarify"},
    {de: "tatsächlich", ru: "actually"},
    {de: "selbst", ru: "even"},
    {de: "regelmäßig", ru: "regularly"},
    {de: "genug", ru: "enough"},
    {de: "der Alltag", ru: "everyday life"},
    {de: "erinnern", ru: "remind"},
    {de: "aufstehen", ru: "get up"},
    {de: "der Rechner", ru: "the computer"},
    {de: "verdammt", ru: "damn"},
    {de: "vertieft", ru: "engrossed"},
    {de: "recherchieren", ru: "do research"},
    {de: "nebenbei", ru: "by the way"},
    {de: "um die Welt", ru: "around the world"},
    {de: "reisen", ru: "travel"},
    {de: "das Aufstehen", ru: "getting up"},
    {de: "ins Bett gehen", ru: "go to bed"},
    {de: "duschen", ru: "take a shower"},
    {de: "das Fahrrad", ru: "the bicycle"},
    {de: "irgendwohin", ru: "somewhere"},
    {de: "im Ohr", ru: "in the ear"},
    {de: "nicht mein Ding", ru: "not my thing"},
    {de: "die Unterhaltung", ru: "the entertainment"},
    {de: "die Sache", ru: "the thing"},
    {de: "mysteriös", ru: "mysteriously"},
    {de: "während", ru: "while"},
    {de: "das Gesicht", ru: "the face"},
    {de: "die Art", ru: "the way"},
    {de: "die Nische", ru: "the niche"},
    {de: "interessieren", ru: "interest"},
    {de: "abdecken", ru: "cover"},
    {de: "nennen", ru: "to name"},
    {de: "im Rahmen", ru: "in the context of"},
    {de: "beschränken", ru: "restrict"},
    {de: "ein paar", ru: "a few"},
    {de: "die Macke", ru: "the quirk"},
    {de: "die Nachricht", ru: "the message"},
    {de: "anhören", ru: "hear"},
    {de: "bedeuten", ru: "to mean"},
    {de: "im weitesten Sinne", ru: "in the broadest sense"},
    {de: "betreffen", ru: "affect"},
    {de: "einordnen", ru: "comment on"},
    {de: "bewerten", ru: "evaluate"},
    {de: "angenehm", ru: "enjoyable"},
    {de: "das Putzen", ru: "the cleaning"},
    {de: "brauchen", ru: "need"},
    {de: "normalerweise", ru: "normally"},
    {de: "aufsparen", ru: "save"},
    {de: "lieblings", ru: "favorite"},
    {de: "aufbewahren", ru: "keep"},
    {de: "abonnieren", ru: "subscribe"},
    {de: "entscheiden", ru: "decide"},
    {de: "löschen", ru: "delete"},
    {de: "das Fahrradfahren", ru: "bicycling"},
    {de: "nach Hause", ru: "go home"},
    {de: "Geschirr spülen", ru: "do the dishes"},
    {de: "sich läppern", ru: "to add up"},
    {de: "der Ausdruck", ru: "the expression"},
    {de: "dran sein", ru: "to be next"},
    {de: "trotzdem", ru: "nevertheless"},
    {de: "fest und flauschig", ru: "firm and fluffy"},
    {de: "quatschen", ru: "to chat"},
    {de: "im Grunde genommen", ru: "for all intents and purposes"},
    {de: "ernst", ru: "serious"},
    {de: "der Quatsch", ru: "the silliness"},
    {de: "auf den Keks gehen", ru: "to get on one's nerves"},
    {de: "das Entspannen", ru: "the relaxation"},
    {de: "die Sendung", ru: "the program"},
    {de: "darum gehen", ru: "to be about"},
    {de: "erfahren", ru: "to learn"},
    {de: "der Hintergrund", ru: "the background"},
    {de: "der Textilarbeiter", ru: "the textile worker"},
    {de: "das Außergewöhnliche", ru: "the extraordinary"},
    {de: "der Umbruch", ru: "the change"},
    {de: "darstellen", ru: "to portray"},
    {de: "tiefer gehen", ru: "to go deeper"},
    {de: "dauern", ru: "to take time"},
    {de: "die Reportage", ru: "the documentary"},
    {de: "die Fernsehsendung", ru: "the television program"},
    {de: "die Empfehlung", ru: "the recommendation"},
    {de: "ansprechen", ru: "to address"},
    {de: "besprechen", ru: "to discuss"},
    {de: "konkret", ru: "concrete"},
    {de: "nachschauen", ru: "to take a look"},
    {de: "aufschreiben", ru: "to write down"},
    {de: "anhören", ru: "to listen to"},
    {de: "funktionieren", ru: "to work"},
    {de: "umgekehrt", ru: "the other way around"},
    {de: "an jemanden wenden", ru: "to contact someone"},
    {de: "verstehem", ru: "do you see"},
    {de: "der Sinn", ru: "that makes sense"},
    {de: "aussehen", ru: "to look like"},
    {de: "auf jeden Fall", ru: "in any case"},
    {de: "Fragen stellen", ru: "to ask questions"},
    {de: "beantworten", ru: "to reply"},
    {de: "in Audio Form", ru: "to manage something"},
    {de: "etwas hinkriegen", ru: "to send"},
    {de: "schicken", ru: "to play"},
    {de: "einspielen", ru: "encouraging"},
    {de: "ermutigend", ru: "to contact us"},
    {de: "an uns wenden", ru: "to get in touch"},
    {de: "melden", ru: "the bonus point"},
    {de: "der Extrapunkt", ru: "in any case"},
    {de: "aussuchen", ru: "to choose"},
    {de: "aus aktuellem Anlass", ru: "on current occasions"},
    {de: "einbringen", ru: "to introduce"},
    {de: "das läppert sich", ru: "that's adding up (to something big)"},
    {de: "nachschauen", ru: "to have a look"},
    {de: "wo etwas herkommt", ru: "where something comes from"},
    {de: "zusammenkommen", ru: "to come together"},
    {de: "ausmachen", ru: "to amount to"},
    {de: "der Zusammenhang", ru: "the context"},
    {de: "zusammenhängen mit", ru: "to have to do with"},
    {de: "der fester Ausdruck", ru: "the fixed expression"},
    {de: "die Wortherkunft", ru: "the origin of the word"},
    {de: "das Mittelniederdeutsch", ru: "the Middle Low German"},
    {de: "der Löffel", ru: "the spoon"},
    {de: "der Zucker", ru: "the sugar"},
    {de: "tun", ru: "to put in"},
    {de: "der Begriff", ru: "the term"},
    {de: "süß", ru: "sweet"},
    {de: "nichts ausmachen", ru: "to not matter"},
    {de: "der Topf", ru: "the pot"},
    {de: "einen drauf machen (ugs)", ru: "to party (colloq)"},
    {de: "feiern", ru: "to celebrate"},
    {de: "auswählen", ru: "to select"},
    {de: "einen drauf machen", ru: "to party (colloq)"},
    {de: "der Akkusativ", ru: "the accusative"},
    {de: "das unbestimmte Objekt", ru: "the indefinite object"},
    {de: "etwas Außergewöhnliches", ru: "something out of the ordinary"},
    {de: "eskalieren", ru: "to escalate"},
    {de: "ausgiebig", ru: "profusely"},
    {de: "die Jugendlichen", ru: "the youth"},
    {de: "die Katastrophe", ru: "the catastrophe"},
    {de: "ein positiv besetzter Begriff", ru: "a term with a positive connotation"},
    {de: "das Besäufnis", ru: "the (heavy) drinking"},
    {de: "in einer positiven Weise", ru: "in a positive way"},
    {de: "außer Kontrolle geraten", ru: "to get out of hand"},
    {de: "betrunken", ru: "drunken"},
    {de: "der Kater", ru: "the hangover"},
    {de: "die Vorsicht", ru: "the caution"},
    {de: "das Schlimmste", ru: "the worst"},
    {de: "heiraten", ru: "to get married"},
    {de: "das Wochenende", ru: "the weekend"},
    {de: "anreisen", ru: "to arrive"},
    {de: "die Hochzeit", ru: "the wedding"},
    {de: "der Trauzeuge", ru: "the best man"},
    {de: "die Trauzeugin", ru: "the maid of honor"},
    {de: "die Ankündigung", ru: "the announcement"},
    {de: "aussprechen", ru: "to pronounce"},
    {de: "herumsitzen", ru: "to sit around"},
    {de: "nach oben prosten", ru: "to toast"},
    {de: "das Brautpaar", ru: "the bride and groom"},
    {de: "das Standesamt", ru: "the registry office"},
    {de: "in einem positiven Sinne", ru: "in a positive sense"},
    {de: "wunderbar", ru: "wonderful"},
    {de: "das nervt", ru: "that is annoying"},
    {de: "die Fahrradinfrastruktur", ru: "the bicycle infrastructure"},
    {de: "die Lieblingskategorie", ru: "the favorite category"},
    {de: "witzigerweise", ru: "funnily enough"},
    {de: "beliebt", ru: "popular"},
    {de: "schneiden", ru: "to edit"},
    {de: "sich aufregen", ru: "to get worked up"},
    {de: "abwechselnd", ru: "in turns"},
    {de: "gleichzeitig", ru: "at the same time"},
    {de: "der Fahrradfahrer", ru: "the cyclist"},
    {de: "ganz ehrlich", ru: "in all honesty"},
    {de: "das Gebiet", ru: "the area"},
    {de: "bauen", ru: "to build"},
    {de: "überhaupt gar nicht", ru: "not at all"},
    {de: "die Großstadt", ru: "the metropolis"},
    {de: "dementsprechend", ru: "accordingly"},
    {de: "das Unding", ru: "the absurdity"},
    {de: "der Fahrradweg", ru: "the bicycle path"},
    {de: "holprig", ru: "bumpy"},
    {de: "unsicher", ru: "unsafe"},
    {de: "schmal", ru: "narrow"},
    {de: "das Büro", ru: "the office"},
    {de: "die Spur", ru: "the track"},
    {de: "breit", ru: "broad"},
    {de: "der Gehweg", ru: "the sidewalk"},
    {de: "der Bürgersteig", ru: "the sidewalk"},
    {de: "dazwischen", ru: "in between"},
    {de: "mitbedenken", ru: "to (also) consider"},
    {de: "das Ganze", ru: "the whole thing"},
    {de: "umbauen", ru: "to remodel"},
    {de: "die Autotür", ru: "the car door"},
    {de: "überholen", ru: "to overtake sb."},
    {de: "der Platz", ru: "the space"},
    {de: "ungemütlich", ru: "uncomfortable"},
    {de: "die Spur", ru: "the lane"},
    {de: "zustehen", ru: "to be entitled to"},
    {de: "die Art und Weise", ru: "the manner"},
    {de: "etwas dabei belassen", ru: "to leave something at that"},
    {de: "sich wünschen", ru: "to wish"},
    {de: "teilen", ru: "to share"},
    {de: "sportlich", ru: "sportily"},
    {de: "selbstsicher", ru: "confident"},
    {de: "der Rentner", ru: "the retiree"},
    {de: "beängstigt", ru: "terrified"},
    {de: "abschreckend", ru: "discouraging"},
    {de: "sich etwas erlauben können", ru: "to be able to afford something"},
    {de: "die Zukunft", ru: "the future"},
    {de: "falsch laufen", ru: "to go wrong"},
    {de: "der Satz", ru: "the sentence"},
    {de: "die Hälfte der Zeit", ru: "half the time"},
    {de: "der Verkehr", ru: "the traffic"},
    {de: "die Strecke", ru: "the route"},
    {de: "die Heimatstadt", ru: "the hometown"},
    {de: "freiwillig", ru: "voluntarily"},
    {de: "die Promenade", ru: "the promenade"},
    {de: "die Stadtbefestigung", ru: "the city fortification"},
    {de: "der Fußgänger", ru: "the pedestrian"},
    {de: "herumfahren", ru: "to ride around"},
    {de: "die Schnellstraße", ru: "the highway"},
    {de: "die Masse", ru: "the mass"},
    {de: "unterm Auto liegen", ru: "to be run over (colloq)"},
    {de: "abbiegen", ru: "to turn"},
    {de: "die Kreuzung", ru: "the intersection"},
    {de: "die traurige Wahrheit", ru: "the sad truth"},
    {de: "der Mensch", ru: "the human being"},
    {de: "sterben", ru: "to die"},
    {de: "der Fahrradunfall", ru: "the bicycle accident"},
    {de: "selbstverständlich", ru: "of course"},
    {de: "bremsen", ru: "to brake"},
    {de: "in der letzten Minute", ru: "at the last minute"},
    {de: "sich erschrecken", ru: "to frighten"},
    {de: "unterm Strich", ru: "all in all"},
    {de: "der Fehler", ru: "the fault"},
    {de: "in Berührung kommen", ru: "to come into contact"},
    {de: "die Minderheit", ru: "the minority"},
    {de: "die Niederlande", ru: "the Netherlands"},
    {de: "Dänemark", ru: "Denmark"},
    {de: "das Luxusproblem", ru: "the luxury problem"},
    {de: "überhaupt", ru: "at all"},
    {de: "bewegen", ru: "to move"},
    {de: "das stimmt", ru: "that's true"},
    {de: "sich aufregen", ru: "to get excited"},
    {de: "nerven", ru: "to annoy"},
    {de: "bespielen", ru: "to fill"},
    {de: "ehrenwert", ru: "honorable"},
    {de: "die Herbstgefühle", ru: "autumn feelings"},
    {de: "der Herbst", ru: "autumn"},
    {de: "überraschend", ru: "astonishing"},
    {de: "einsetzen", ru: "to start"},
    {de: "die Heizung", ru: "the heater"},
    {de: "die Jacke", ru: "the jacket"},
    {de: "der Wetterumschwung", ru: "the weather change"},
    {de: "die Gemütlichkeit", ru: "the coziness"},
    {de: "empfinden", ru: "to feel"},
    {de: "verspüren", ru: "to experience"},
    {de: "draußen", ru: "outside"},
    {de: "drinnen", ru: "indoors"},
    {de: "die Kerze", ru: "the candle"},
    {de: "die Lichter", ru: "the lights"},
    {de: "herzlich", ru: "warm-hearted"},
    {de: "in unseren Breitengraden", ru: "in our latitudes"},
    {de: "die Jahreszeit", ru: "the season"},
    {de: "beginnen", ru: "to start"},
    {de: "enden", ru: "to end"},
    {de: "der Kakao", ru: "the hot chocolate"},
    {de: "gemütlich", ru: "homey"},
    {de: "verbringen", ru: "to spend"},
    {de: "der Urlaubsplan", ru: "the holiday plan"},
    {de: "ausreisen", ru: "to emigrate"},
    {de: "besonders", ru: "special"},
    {de: "seit Längerem", ru: "for quite some time"},
    {de: "verfolgen", ru: "to follow"},
    {de: "philosophisch", ru: "philosophical"},
    {de: "nachdenken", ru: "to ponder"},
    {de: "befragen", ru: "to question"},
    {de: "die Folge", ru: "the episode"},
    {de: "obsessiv", ru: "obsessively"},
    {de: "das Buch", ru: "the book"},
    {de: "das Abenteuer", ru: "the adventure"},
    {de: "die Psychologie", ru: "the psychology"},
    {de: "suchen", ru: "to search"},
    {de: "lesen", ru: "to read"},
    {de: "soziologisch", ru: "sociological"},
    {de: "wichtig", ru: "important"},
    {de: "die kommunistische Diktatur", ru: "the communist dictatorship"},
    {de: "das Alter", ru: "the age"},
    {de: "kapieren (ugs)", ru: "to comprehend (colloq)"},
    {de: "ablaufen", ru: "to expire"},
    {de: "unterhalten", ru: "to have a conversation"},
    {de: "der Baum", ru: "the tree"},
    {de: "beweisen", ru: "to prove"},
    {de: "anfassen", ru: "to touch"},
    {de: "schaffen", ru: "to accomplish"},
    {de: "auslachen", ru: "to ridicule"},
    {de: "dumm", ru: "stupid"},
    {de: "der Ast", ru: "the branch"},
    {de: "verprügeln", ru: "to beat up"},
    {de: "der Beweis", ru: "the proof"},
    {de: "die Geschichte", ru: "the history"},
    {de: "kaufen", ru: "to buy"},
    {de: "das Standardbuch", ru: "the standard book"},
    {de: "die Geschichte der Philosophie", ru: "the history of philosophy"},
    {de: "der Krieg", ru: "the war"},
    {de: "anfangen", ru: "to start"},
    {de: "davon wegkommen", ru: "to get away from something"},
    {de: "sozusagen", ru: "so to speak"},
    {de: "die besten Köpfe", ru: "the best minds"},
    {de: "verstehen", ru: "to grasp"},
    {de: "die Materie", ru: "the matter"},
    {de: "der Gedanke", ru: "the thought"},
    {de: "der Geist", ru: "the spirit"},
    {de: "harter Stoff (ugs)", ru: "difficult subject (colloq)"},
    {de: "die Einleitung", ru: "the introduction"},
    {de: "spannend", ru: "fascinating"},
    {de: "vornehmen", ru: "to have planned"},
    {de: "bescheuert", ru: "to be nuts"},
    {de: "studieren", ru: "to study"},
    {de: "die Perspektive", ru: "the perspective"},
    {de: "mit Sicherheit", ru: "for sure"},
    {de: "nutzen", ru: "to use"},
    {de: "bestimmte Fragen", ru: "specific questions"},
    {de: "das Philosophische", ru: "the philosophical"},
    {de: "natürlich", ru: "of course"},
    {de: "der Zuschauer", ru: "the spectator"},
    {de: "die Gewissheit", ru: "the certainty"},
    {de: "die Sicherheit", ru: "the security"},
    {de: "der Glauben", ru: "the faith"},
    {de: "die Unsicherheit", ru: "the uncertainty"},
    {de: "die Taktik", ru: "the tactics"},
    {de: "erklären", ru: "to explain"},
    {de: "sich mit etwas abfinden", ru: "come to terms with something"},
    {de: "der Großteil", ru: "the majority"},
    {de: "der Bereich", ru: "the area"},
    {de: "erfrischend", ru: "refreshingly"},
    {de: "diskutieren", ru: "to debate"},
    {de: "die Meinung", ru: "the opinion"},
    {de: "der Exkurs", ru: "the digression"},
    {de: "das Gehirn", ru: "the brain"},
    {de: "insofern", ru: "therefore"},
    {de: "die Grammatik", ru: "the grammar"},
    {de: "trivial", ru: "trivial"},
    {de: "der Sinn des Lebens", ru: "the meaning of life"},
    {de: "Bock haben (ugs)", ru: "to be up for it (colloq)"},
    {de: "etwas klarstellen", ru: "to clarify something"},
    {de: "die Werbung", ru: "the advertisement"},
    {de: "in Berlin spielen", ru: "to be set in Berlin"},
    {de: "das Besondere", ru: "the special thing"},
    {de: "der Schnitt", ru: "the cut"},
    {de: "unglaublich", ru: "unbelievable"},
    {de: "die Hauptperson", ru: "the main character"},
    {de: "verstehen", ru: "to understand"},
    {de: "im Original", ru: "in the original"},
    {de: "die Untertitel", ru: "the subtitles"},
    {de: "der Lieblingsfilm", ru: "the favorite movie"},
    {de: "spannend", ru: "intriguing"},
    {de: "einzeln", ru: "single"},
    {de: "die Zeitung", ru: "the newspaper"},
    {de: "empfehlen", ru: "to recommend"},
    {de: "harter Tobak (ugs)", ru: "tough stuff (colloq)"},
    {de: "angenehm", ru: "pleasant"},
    {de: "beeindruckt", ru: "impressed"},
    {de: "gefesselt", ru: "captivated"},
    {de: "die Tochter", ru: "the daughter"},
    {de: "der Einwohner", ru: "the inhabitant"},
    {de: "passieren", ru: "to transpire"},
    {de: "eine Welt bricht zusammen", ru: "a world collapses"},
    {de: "feststellen", ru: "to notice"},
    {de: "freiwillig", ru: "of one's own free will"},
    {de: "auswandern", ru: "to emigrate"},
    {de: "eine krasse Geschichte", ru: "a crazy story"},
    {de: "fesselnd", ru: "captivating"},
    {de: "das Krasse", ru: "the incredible thing"},
    {de: "verraten", ru: "to reveal"},
    {de: "die Zeiten", ru: "the times"},
    {de: "das Wichtigste", ru: "the contact"},
    {de: "der Wunsch", ru: "most important"},
    {de: "bewirken", ru: "the wish"},
    {de: "die Herausforderung", ru: "to bring about"},
    {de: "aufgeben", ru: "to give up"},
    {de: "der Suizidgedanke", ru: "the suicidal tendency"},
    {de: "das Phänomen", ru: "the phenomenon"},
    {de: "anziehen", ru: "to draw"},
    {de: "ausschließlich", ru: "exclusively"},
    {de: "eine krasse Geschichte", ru: "a horrible story"},
    {de: "damit umgehen", ru: "to deal with it"},
    {de: "empfehlenswert", ru: "recommendable"},
    {de: "das Beeindruckendste", ru: "the most impressive thing"},
    {de: "im negativen Sinne", ru: "in the negative"},
    {de: "verlinken", ru: "to link"},
    {de: "erzählen", ru: "to tell"},
    {de: "Holländisch", ru: "Dutch"},
    {de: "lustig", ru: "amusingly"},
    {de: "das Niveau", ru: "the level"},
    {de: "genießen", ru: "to enjoy"},
    {de: "das Lied", ru: "the song"},
    {de: "versuchen", ru: "to try"},
    {de: "raushören", ru: "to listen to the lyrics"},
    {de: "übersetzen", ru: "to translate"},
    {de: "formulieren", ru: "to express"},
    {de: "überlegen", ru: "to have thought out"},
    {de: "mit auf den Weg geben", ru: "to send away with"},
    {de: "die Hausaufgabe", ru: "the homework"},
    {de: "überlassen sein", ru: "to be left to you"},
    {de: "die Hausaufgaben", ru: "the homework"},
    {de: "die Klassenarbeit", ru: "the class test"},
    {de: "die neunziger Jahre", ru: "the nineties"},
    {de: "bekannt", ru: "well-known"},
    {de: "zwangsläufig", ru: "inevitably"},
    {de: "die Mischung", ru: "the mixture"},
    {de: "entscheiden", ru: "to decide"},
    {de: "auf eine deutsche Art", ru: "in a German way"},
    {de: "das Ende", ru: "the end"},
    {de: "mindestens", ru: "at least"},
    {de: "eskalieren", ru: "escalate"},
    {de: "lauthals", ru: "at the top of one's voice"},
    {de: "vorspielen", ru: "to play (for someone)"},
    {de: "vorsingen", ru: "to sing (for someone)"},
    {de: "der Refrain", ru: "the chorus"},
    {de: "auswendig kennen", ru: "to know by heart"},
    {de: "der/die Herzallerliebste(r)", ru: "the beloved (person)"},
    {de: "aus dem Lande (ugs)", ru: "gone (colloq)"},
    {de: "heulen", ru: "to cry"},
    {de: "auf jemanden scharf sein", ru: "to have the hots for sb"},
    {de: "das Glück ist mit den Dummen", ru: "fortune favors fools"},
    {de: "jein", ru: "(in between yes and no)"},
    {de: "älter", ru: "older"},
    {de: "mitsingen", ru: "sing along"},
    {de: "schnell", ru: "fast"},
    {de: "die Neunziger", ru: "the nineties"},
    {de: "die Zweitausender", ru: "the two-thousanders"},
    {de: "anwesend sein", ru: "to be present"},
    {de: "der Klassiker", ru: "the classic"},
    {de: "entgegenschlagen", ru: "to come back at you"},
    {de: "umwerfend", ru: "staggering"},
    {de: "die Mitgliedschaft", ru: "the membership"},
    {de: "das Mitglied", ru: "the member"},
    {de: "abwickeln", ru: "to process"},
    {de: "die Zusatzmöglichkeit", ru: "the additional possibility"},
    {de: "anmelden", ru: "to register"},
    {de: "die Vokabelliste", ru: "the vocabulary list"},
    {de: "mitlaufen", ru: "to run along"},
    {de: "funktionieren", ru: "how it works"},
    {de: "zum Beispiel", ru: "for instance"},
    {de: "beschreiben", ru: "to describe"},
    {de: "benachrichtigen", ru: "to inform"},
    {de: "das Zusatzmaterial", ru: "the additional material"},
    {de: "zufrieden", ru: "satisfied"},
    {de: "die Skala", ru: "the scale"},
    {de: "bewerten", ru: "to rate"},
    {de: "übertreiben", ru: "to exaggerate"},
    {de: "zuhören", ru: "to listen"},
    {de: "fünf Sterne", ru: "five stars"},
    {de: "das Höchste", ru: "the highest"},
    {de: "etwas sein lassen", ru: "to stop doing something"},
    {de: "sich von selbst verstehen", ru: "to go without saying"},
    {de: "sich etwas sparen (ugs)", ru: "to not do something (colloq)"}
  ],

  EG 3 - Alles in Ordnung: [
    {de: "gut gelaunt", ru: "in a good mood"},
    {de: "aufzeichnen", ru: "to record"},
    {de: "in der Regel", ru: "usually"},
    {de: "der Zuschauer", ru: "the viewer"},
    {de: "schwierig", ru: "difficult"},
    {de: "Vokabelhilfe", ru: "vocabulary helper"},
    {de: "schneiden", ru: "to edit"},
    {de: "eigentlich", ru: "actually"},
    {de: "nur ganz leicht", ru: "just very slightly"},
    {de: "wahnsinnig", ru: "insanely"},
    {de: "der Spaß", ru: "the fun"},
    {de: "die Nachricht", ru: "the message"},
    {de: "anfangen", ru: "to start"},
    {de: "sich freuen", ru: "to be delighted"},
    {de: "irgendwann", ru: "someday"},
    {de: "noch länger", ru: "even longer"},
    {de: "schaffen", ru: "to manage"},
    {de: "genau richtig", ru: "just right"},
    {de: "Bock haben (ugs)", ru: "to want (colloq)"},
    {de: "besprechen", ru: "to discuss"},
    {de: "zu kurz", ru: "too short"},
    {de: "statt", ru: "instead of"},
    {de: "erstmal", ru: "for now"},
    {de: "drücken", ru: "to press"},
    {de: "erlaubt sein", ru: "to be allowed"},
    {de: "sich aufsparen", ru: "to save up"},
    {de: "an einem Stück", ru: "in one go"},
    {de: "die Pflicht", ru: "the obligation"},
    {de: "einsteigen", ru: "to get in"},
    {de: "die Anmerkung", ru: "the note"},
    {de: "der Klimawandel", ru: "climate change"},
    {de: "sonntags geschlossen", ru: "closed on Sundays"},
    {de: "der Ärger", ru: "the anger"},
    {de: "das Fahrradgeschäft", ru: "the bicycle shop"},
    {de: "das Wochenende", ru: "the weekend"},
    {de: "die Angelegenheit", ru: "the matter"},
    {de: "die Hochzeit", ru: "the wedding"},
    {de: "das Ergebnis", ru: "the result"},
    {de: "sich aufs Glatteis begeben (ugs)", ru: "to be on a slippery slope (colloq)"},
    {de: "die Einzelhandelskette", ru: "the retail chain"},
    {de: "die Kindheit", ru: "the childhood"},
    {de: "unvorstellbar", ru: "unimaginable"},
    {de: "aufregen", ru: "to get mad"},
    {de: "die Möglichkeit", ru: "the possibility"},
    {de: "heilig", ru: "sacred"},
    {de: "der Feiertag", ru: "the holiday"},
    {de: "feiern", ru: "to celebrate"},
    {de: "traurig", ru: "sad"},
    {de: "zum ersten Mal", ru: "for the first time"},
    {de: "Weihnachten", ru: "Christmas"},
    {de: "im Prinzip", ru: "basically"},
    {de: "strömen", ru: "to pour"},
    {de: "das Angebot", ru: "the offer"},
    {de: "die Vorstellung", ru: "the idea"},
    {de: "der Familienfeiertag", ru: "the family holiday"},
    {de: "verrückt", ru: "insane"},
    {de: "jmd. Recht geben", ru: "agree with sb."},
    {de: "der Kleiderladen", ru: "the clothes shop"},
    {de: "so bleiben", ru: "to stay that way"},
    {de: "die Firma", ru: "the company"},
    {de: "die Kette", ru: "the chain"},
    {de: "die Leidenschaft", ru: "the passion"},
    {de: "in der Regel", ru: "generally"},
    {de: "der Mitarbeiter", ru: "the employee"},
    {de: "gerade deswegen", ru: "precisely because of this"},
    {de: "geschlossen", ru: "closed"},
    {de: "auf etw. achten", ru: "to look out for sth."},
    {de: "schaden", ru: "to harm"},
    {de: "pleite gehen", ru: "to go bankrupt"},
    {de: "das Gesetz", ru: "the law"},
    {de: "der Ladenbetreiber", ru: "the shopkeeper"},
    {de: "ruinieren", ru: "to ruin"},
    {de: "die Kneipe", ru: "the pub"},
    {de: "rauchen", ru: "to smoke"},
    {de: "das Recht", ru: "the right"},
    {de: "die Freiheit", ru: "freedom"},
    {de: "schrecklich", ru: "terrible"},
    {de: "vernünftig", ru: "reasonably"},
    {de: "abwägen", ru: "to weigh"},
    {de: "auf Krawall gebürstet sein (ugs)", ru: "to be ready for a riot (colloq)"},
    {de: "der Späti (Berlin)", ru: "the kiosk (Berlin)"},
    {de: "keine Ahnung", ru: "no idea"},
    {de: "hilfreich", ru: "helpful"},
    {de: "das Wörterbuch", ru: "the dictionary"},
    {de: "der Skandal", ru: "the scandal"},
    {de: "vorkommen", ru: "to occur"},
    {de: "bedeuten", ru: "to mean"},
    {de: "kämpfen", ru: "to fight"},
    {de: "der Konflikt", ru: "the conflict"},
    {de: "in Kauf nehmen", ru: "to tolerate"},
    {de: "der Krawall", ru: "the riot"},
    {de: "der Krach", ru: "the ruckus"},
    {de: "streiten", ru: "to argue"},
    {de: "die Diskussion", ru: "the discussion"},
    {de: "der Streit", ru: "the quarrel"},
    {de: "die Meinung", ru: "the opinion"},
    {de: "sich einmischen", ru: "to interfere"},
    {de: "beleidigen", ru: "to insult"},
    {de: "die Entschuldigung", ru: "the apology"},
    {de: "verzeihen", ru: "to forgive"},
    {de: "die Vergebung", ru: "the forgiveness"},
    {de: "die Freundschaft", ru: "the friendship"},
    {de: "der Konfliktlösungsweg", ru: "the conflict resolution method"},
    {de: "die Lösung", ru: "the solution"},
    {de: "der Kompromiss", ru: "the compromise"},
    {de: "nachgeben", ru: "to give in"},
    {de: "die Verantwortung", ru: "the responsibility"},
    {de: "zugeben", ru: "to admit"},
    {de: "die Ehrlichkeit", ru: "the honesty"},
    {de: "die Wahrheit", ru: "the truth"},
    {de: "lügen", ru: "to lie"},
    {de: "die Täuschung", ru: "the deception"},
    {de: "der Betrug", ru: "the fraud"},
    {de: "vertrauen", ru: "to trust"},
    {de: "das Vertrauen", ru: "the trust"},
    {de: "die Loyalität", ru: "the loyalty"},
    {de: "verraten", ru: "to betray"},
    {de: "die Unterstützung", ru: "the support"},
    {de: "helfen", ru: "to help"},
    {de: "die Hilfe", ru: "the help"},
    {de: "unterstützen", ru: "to support"},
    {de: "die Zusammenarbeit", ru: "the cooperation"},
    {de: "kooperieren", ru: "to cooperate"},
    {de: "gemeinsam", ru: "together"},
    {de: "der Erfolg", ru: "the success"},
    {de: "gelingen", ru: "to succeed"},
    {de: "versagen", ru: "to fail"},
    {de: "die Chance", ru: "the opportunity"},
    {de: "die Möglichkeit", ru: "the possibility"},
    {de: "probieren", ru: "to try"},
    {de: "das Experiment", ru: "the experiment"},
    {de: "erforschen", ru: "to explore"},
    {de: "die Entdeckung", ru: "the discovery"},
    {de: "die Wissenschaft", ru: "the science"},
    {de: "forschen", ru: "to research"},
    {de: "die Technik", ru: "the technology"},
    {de: "entwickeln", ru: "to develop"},
    {de: "die Entwicklung", ru: "the development"},
    {de: "die Erfindung", ru: "the invention"},
    {de: "erfinden", ru: "to invent"},
    {de: "die Idee", ru: "the idea"},
    {de: "das Konzept", ru: "the concept"},
    {de: "planen", ru: "to plan"},
    {de: "die Planung", ru: "the planning"},
    {de: "organisieren", ru: "to organize"},
    {de: "die Organisation", ru: "the organization"},
    {de: "die Struktur", ru: "the structure"},
    {de: "die Funktion", ru: "the function"},
    {de: "benutzen", ru: "to use"},
    {de: "anwenden", ru: "to apply"},
    {de: "die Anwendung", ru: "the application"},
    {de: "die Lösung", ru: "the solution"},
    {de: "reparieren", ru: "to repair"},
    {de: "die Reparatur", ru: "the repair"},
    {de: "verbessern", ru: "to improve"},
    {de: "die Verbesserung", ru: "the improvement"},
    {de: "kontrollieren", ru: "to control"},
    {de: "die Kontrolle", ru: "the control"},
    {de: "die Sicherheit", ru: "the safety"},
    {de: "sicher", ru: "safe"},
    {de: "gefahrlich", ru: "dangerous"},
    {de: "das Risiko", ru: "the risk"},
    {de: "vermeiden", ru: "to avoid"},
    {de: "die Vorsicht", ru: "the caution"},
    {de: "aufpassen", ru: "to watch out"},
    {de: "die Verantwortung", ru: "the responsibility"},
    {de: "pflichtbewusst", ru: "conscientious"},
    {de: "pflichtvergessen", ru: "neglectful"},
    {de: "die Regel", ru: "the rule"},
    {de: "befolgen", ru: "to follow"},
    {de: "die Strafe", ru: "the punishment"},
    {de: "bestrafen", ru: "to punish"},
    {de: "das Gesetz", ru: "the law"},
    {de: "die Vorschrift", ru: "the regulation"},
    {de: "einhalten", ru: "to comply"},
    {de: "übertreten", ru: "to violate"},
    {de: "die Ordnung", ru: "the order"},
    {de: "stören", ru: "to disturb"},
    {de: "der Lärm", ru: "the noise"},
    {de: "die Ruhe", ru: "the quiet"},
    {de: "entspannen", ru: "to relax"},
    {de: "die Entspannung", ru: "the relaxation"},
    {de: "ausruhen", ru: "to rest"},
    {de: "die Pause", ru: "the break"},
    {de: "die Freizeit", ru: "the free time"},
    {de: "das Hobby", ru: "the hobby"},
    {de: "spielen", ru: "to play"},
    {de: "lernen", ru: "to learn"},
    {de: "unterrichten", ru: "to teach"},
    {de: "die Bildung", ru: "the education"},
    {de: "die Schule", ru: "the school"},
    {de: "der Unterricht", ru: "the lesson"},
    {de: "der Lehrer", ru: "the teacher"},
    {de: "die Schülerin", ru: "the student"},
    {de: "prüfen", ru: "to examine"},
    {de: "die Prüfung", ru: "the exam"},
    {de: "bestehen", ru: "to pass"},
    {de: "durchfallen", ru: "to fail"},
    {de: "das Studium", ru: "the studies"},
    {de: "die Universität", ru: "the university"},
    {de: "der Kurs", ru: "the course"},
    {de: "die Vorlesung", ru: "the lecture"},
    {de: "das Seminar", ru: "the seminar"},
    {de: "das Lernen", ru: "the learning"},
    {de: "die Fähigkeit", ru: "the skill"},
    {de: "das Wissen", ru: "the knowledge"},
    {de: "die Erfahrung", ru: "the experience"},
    {de: "üben", ru: "to practice"},
    {de: "die Übung", ru: "the exercise"},
    {de: "die Konzentration", ru: "the concentration"},
    {de: "sich erinnern", ru: "to remember"},
    {de: "vergessen", ru: "to forget"},
    {de: "die Aufmerksamkeit", ru: "the attention"},
    {de: "die Notiz", ru: "the note"},
    {de: "aufschreiben", ru: "to write down"},
    {de: "lesen", ru: "to read"},
    {de: "schreiben", ru: "to write"},
    {de: "die Sprache", ru: "the language"},
    {de: "sprechen", ru: "to speak"},
    {de: "verstehen", ru: "to understand"},
    {de: "die Kommunikation", ru: "the communication"},
    {de: "reden", ru: "to talk"},
    {de: "diskutieren", ru: "to discuss"},
    {de: "fragen", ru: "to ask"},
    {de: "antworten", ru: "to answer"},
    {de: "die Frage", ru: "the question"},
    {de: "die Antwort", ru: "the answer"},
    {de: "erklären", ru: "to explain"},
    {de: "die Erklärung", ru: "the explanation"},
    {de: "die Diskussion", ru: "the discussion"},
    {de: "das Gespräch", ru: "the conversation"},
    {de: "die Debatte", ru: "the debate"},
    {de: "die Meinung", ru: "the opinion"},
    {de: "die Perspektive", ru: "the perspective"},
    {de: "die Haltung", ru: "the attitude"},
    {de: "die Überzeugung", ru: "the conviction"},
    {de: "überzeugen", ru: "to convince"},
    {de: "argumentieren", ru: "to argue"},
    {de: "die Logik", ru: "the logic"},
    {de: "die Analyse", ru: "the analysis"},
    {de: "analysieren", ru: "to analyze"},
    {de: "die Synthese", ru: "the synthesis"},
    {de: "kombinieren", ru: "to combine"},
    {de: "die Schlussfolgerung", ru: "the conclusion"},
    {de: "schließen", ru: "to conclude"},
    {de: "die Idee", ru: "the idea"},
    {de: "die Kreativität", ru: "the creativity"},
    {de: "kreativ", ru: "creative"},
    {de: "die Vorstellungskraft", ru: "the imagination"},
    {de: "fantasieren", ru: "to imagine"},
    {de: "die Inspiration", ru: "the inspiration"},
    {de: "inspirieren", ru: "to inspire"},
    {de: "die Motivation", ru: "the motivation"},
    {de: "motivieren", ru: "to motivate"},
    {de: "die Initiative", ru: "the initiative"},
    {de: "initiativ", ru: "proactive"},
    {de: "die Verantwortung", ru: "the responsibility"},
    {de: "verantwortlich", ru: "responsible"},
    {de: "führen", ru: "to lead"},
    {de: "die Führung", ru: "the leadership"},
    {de: "die Organisation", ru: "the organization"},
    {de: "organisieren", ru: "to organize"},
    {de: "die Planung", ru: "the planning"},
    {de: "planen", ru: "to plan"},
    {de: "die Strategie", ru: "the strategy"},
    {de: "strategisch", ru: "strategic"},
    {de: "das Projekt", ru: "the project"},
    {de: "das Team", ru: "the team"},
    {de: "zusammenarbeiten", ru: "to collaborate"},
    {de: "die Kooperation", ru: "the cooperation"},
    {de: "die Partnerschaft", ru: "the partnership"},
    {de: "verhandeln", ru: "to negotiate"},
    {de: "die Verhandlung", ru: "the negotiation"},
    {de: "der Kompromiss", ru: "the compromise"},
    {de: "lösen", ru: "to solve"},
    {de: "die Lösung", ru: "the solution"},
    {de: "die Herausforderung", ru: "the challenge"},
    {de: "herausfordern", ru: "to challenge"},
    {de: "das Ziel", ru: "the goal"},
    {de: "erreichen", ru: "to achieve"},
    {de: "das Ergebnis", ru: "the result"},
    {de: "bewerten", ru: "to evaluate"},
    {de: "die Bewertung", ru: "the evaluation"},
    {de: "analysieren", ru: "to analyze"},
    {de: "beobachten", ru: "to observe"},
    {de: "die Beobachtung", ru: "the observation"},
    {de: "die Erfahrung", ru: "the experience"},
    {de: "lernen", ru: "to learn"},
    {de: "entwickeln", ru: "to develop"},
    {de: "die Entwicklung", ru: "the development"},
    {de: "verbessern", ru: "to improve"},
    {de: "die Verbesserung", ru: "the improvement"},
    {de: "die Kompetenz", ru: "the competence"},
    {de: "die Fähigkeit", ru: "the skill"},
    {de: "die Leistung", ru: "the performance"},
    {de: "die Qualität", ru: "the quality"},
    {de: "hochwertig", ru: "high-quality"},
    {de: "bewältigen", ru: "to cope with"},
    {de: "die Bewältigung", ru: "the coping"},
    {de: "die Kommunikation", ru: "the communication"},
    {de: "die Medien", ru: "the media"},
    {de: "die Nachricht", ru: "the news"},
    {de: "die Information", ru: "the information"},
    {de: "informieren", ru: "to inform"},
    {de: "die Recherche", ru: "the research"},
    {de: "recherchieren", ru: "to research"},
    {de: "die Quelle", ru: "the source"},
    {de: "zitieren", ru: "to quote"},
    {de: "die Statistik", ru: "the statistic"},
    {de: "die Zahl", ru: "the number"},
    {de: "die Daten", ru: "the data"},
    {de: "analysieren", ru: "to analyze"},
    {de: "interpretieren", ru: "to interpret"},
    {de: "die Meinung", ru: "the opinion"},
    {de: "die Diskussion", ru: "the discussion"},
    {de: "die Debatte", ru: "the debate"},
    {de: "argumentieren", ru: "to argue"},
    {de: "überzeugen", ru: "to convince"},
    {de: "die Präsentation", ru: "the presentation"},
    {de: "präsentieren", ru: "to present"},
    {de: "die Rede", ru: "the speech"},
    {de: "reden", ru: "to talk"},
    {de: "die Diskussion", ru: "the discussion"},
    {de: "die Meinung", ru: "the opinion"},
    {de: "sich äußern", ru: "to express oneself"},
    {de: "die Kommunikation", ru: "the communication"},
    {de: "verstehen", ru: "to understand"},
    {de: "das Verständnis", ru: "the understanding"},
    {de: "missverstehen", ru: "to misunderstand"},
    {de: "die Sprache", ru: "the language"},
    {de: "die Übersetzung", ru: "the translation"},
    {de: "übersetzen", ru: "to translate"},
    {de: "die Kultur", ru: "the culture"},
    {de: "kulturell", ru: "cultural"},
    {de: "die Gesellschaft", ru: "the society"},
    {de: "soziale Medien", ru: "social media"},
    {de: "die Technik", ru: "the technology"},
    {de: "technologisch", ru: "technological"},
    {de: "digital", ru: "digital"},
    {de: "die Innovation", ru: "the innovation"},
    {de: "innovativ", ru: "innovative"},
    {de: "entwickeln", ru: "to develop"},
    {de: "die Entwicklung", ru: "the development"},
    {de: "die Wissenschaft", ru: "the science"},
    {de: "forschen", ru: "to research"},
    {de: "die Forschung", ru: "the research"},
    {de: "das Experiment", ru: "the experiment"},
    {de: "untersuchen", ru: "to examine"},
    {de: "die Untersuchung", ru: "the examination"},
    {de: "die Theorie", ru: "the theory"},
    {de: "theoretisch", ru: "theoretical"},
    {de: "die Praxis", ru: "the practice"},
    {de: "praktisch", ru: "practical"},
    {de: "die Anwendung", ru: "the application"},
    {de: "anwenden", ru: "to apply"},
    {de: "die Fähigkeit", ru: "the skill"},
    {de: "die Kompetenz", ru: "the competence"},
    {de: "lernen", ru: "to learn"},
    {de: "das Lernen", ru: "the learning"},
    {de: "die Bildung", ru: "the education"},
    {de: "bilden", ru: "to educate"},
    {de: "unterrichten", ru: "to teach"},
    {de: "der Lehrer", ru: "the teacher"},
    {de: "die Lehrerin", ru: "the female teacher"},
    {de: "die Schule", ru: "the school"},
    {de: "der Schüler", ru: "the student"},
    {de: "die Schülerin", ru: "the female student"},
    {de: "die Klasse", ru: "the class"},
    {de: "der Kurs", ru: "the course"},
    {de: "die Prüfung", ru: "the exam"},
    {de: "prüfen", ru: "to test"},
    {de: "bestehen", ru: "to pass"},
    {de: "durchfallen", ru: "to fail"},
    {de: "das Studium", ru: "the studies"},
    {de: "die Universität", ru: "the university"},
    {de: "der Student", ru: "the student"},
    {de: "die Studentin", ru: "the female student"},
    {de: "die Vorlesung", ru: "the lecture"},
    {de: "das Seminar", ru: "the seminar"},
    {de: "die Forschung", ru: "the research"},
    {de: "die Analyse", ru: "the analysis"},
    {de: "analysieren", ru: "to analyze"},
    {de: "die Synthese", ru: "the synthesis"},
    {de: "kombinieren", ru: "to combine"},
    {de: "die Schlussfolgerung", ru: "the conclusion"},
    {de: "schließen", ru: "to conclude"},
    {de: "die Idee", ru: "the idea"},
    {de: "die Kreativität", ru: "the creativity"},
    {de: "kreativ", ru: "creative"},
    {de: "die Vorstellungskraft", ru: "the imagination"},
    {de: "fantasieren", ru: "to imagine"},
    {de: "die Inspiration", ru: "the inspiration"},
    {de: "inspirieren", ru: "to inspire"},
    {de: "die Motivation", ru: "the motivation"},
    {de: "motivieren", ru: "to motivate"},
    {de: "die Initiative", ru: "the initiative"},
    {de: "initiativ", ru: "proactive"},
    {de: "die Verantwortung", ru: "the responsibility"},
    {de: "verantwortlich", ru: "responsible"},
    {de: "führen", ru: "to lead"},
    {de: "die Führung", ru: "the leadership"},
    {de: "die Organisation", ru: "the organization"},
    {de: "organisieren", ru: "to organize"},
    {de: "die Planung", ru: "the planning"},
    {de: "planen", ru: "to plan"}
  ],
  
  3: [
    {de: "", ru: ""}
  ]
};